function f_a_sym = create_f_a(x,y,z)
%CREATE_F_A
%    F_A_SYM = CREATE_F_A(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    28-Nov-2021 23:23:39

f_a_sym = [x.*-3.0-6.0;y.*-3.0;z.*-3.0];
